### PR TITLE
Add excludeDirs option

### PR DESCRIPTION
**Pull request by NikitaFeodonit**
> would you mind to make that changes and to do a seperate pull request for only that feature?
> P.S. I think it will be more consequent to use "excludeDirs" and "excludeFiles" as parameter names

I did. Sorry for the mess with PullRequestes.

### CODE REVIEW

**Comment by individual-it** [comment]
Thank yoi!
I've merged but reverted your "Fixes the backup of complete drives" commit because I cannot see why we need that.
Could you explain why you have added that code?

**Comment by NikitaFeodonit** [comment]
> Could you explain why you have added that code?

My config file:

```
[Common]
backupSources=E:\
backupDestination=Y:\z_Backup\Disk_E
Logfile=E:\Programs\Backup\ntfs-hardlink-backup\logs
backupsToKeep=30
localSubnetOnly=true
NoShadowCopy=false
splice=true
backupModeACLs=true
```

I run it from folder
E:\Programs\Backup\ntfs-hardlink-backup\
with command
```
%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command "& E:\Programs\Backup\ntfs-hardlink-backup\bat\ntfs-hardlink-backup.ps1 -iniFile E:\Programs\Backup\ntfs-hardlink-backup\bat\backup-disk-e.ini"
```
and then backup folder name is
ntfs-hardlink-backup - 2015-01-25 13-39-45

When I began to understand, then in [line of code] (https://github.com/individual-it/ntfs-hardlink-backup/blob/master/ntfs-hardlink-backup.ps1#L921)
```
$backup_source_folder = split-path $backup_source -leaf
```
variable $backup_source_folder == ntfs-hardlink-backup
Why, I do not know.

**Comment by NikitaFeodonit** [comment]
$backup_source == ""

**Comment by individual-it** [comment]
I've just tested it on Windows7 with this configuration, what is basically yours but with other path:

    [Common]
    backupSources=D:\
    backupDestination=C:\tmp\z_Backup\Disk_E
    Logfile=C:\logs\backup_nikita.log
    backupsToKeep=30
    localSubnetOnly=true
    NoShadowCopy=false
    splice=true
    backupModeACLs=true

It has done the backup without a problem.
I've used the currect version of the tool. https://github.com/individual-it/ntfs-hardlink-backup/blob/724dae559d95e247da3b59a1ca37ff89ff7b146e/ntfs-hardlink-backup.ps1
What version of ln, powershell and windows are you using?

**Comment by NikitaFeodonit** [comment]
> What version of ln, powershell and windows are you using?

ln -- Version 2.8.6.1

PowerShell
```
PS Y:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

Windows 7 Professional SP1
```
PS Y:\> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      1      7601   65536
```

**Comment by NikitaFeodonit** [comment]
I found this. If
backupSources=C:\
and I run command
```
%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command "& E:\Programs\Backup\ntfs-hardlink-backup\bat\ntfs-hardlink-backup-proba.ps1 -iniFile E:\Programs\Backup\ntfs-hardlink-backup\bat\backup-disk.ini"
```
from folder in drive C: (for example C:\Users\) then backup folder name is
Users - 2015-01-27 11-17-42

If I run that command from drive != backupSources then all is ok.

**Comment by NikitaFeodonit** [comment]
With my patch is ok for all case.

**Comment by individual-it** [comment]
I finally could reproduce the problem. Thanks for the testing!
C: is interpreted as relative path to the local working directory but C:\ is interpreted as the root of the drive.
See also https://stackoverflow.com/questions/23955968/path-with-no-slash-after-drive-letter-and-colon-what-does-it-point-to

Because we strip away the "\" fahrer up to make ln.exe not to interpret it as an escape character we left with C: only here. 

Please fork the current version and make a new pull request.
Sorry for the extra work.

**Comment by NikitaFeodonit** [comment]
> Sorry for the extra work.

All is ok :)

> I finally could reproduce the problem.

This is important :)

**Pull request merged**
